version: '3.7'

services:
  db:
    build: ./data
    container_name: "${CONTAINER_PREFIX}_db"
    restart: 'always'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    volumes:
     - ./data/mysql:/var/lib/mysql
     - ./data/init:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_RANDOM_ROOT_PASSWORD=yes
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
     - TZ
    networks:
     - localnet
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.2
    container_name: "${CONTAINER_PREFIX}_phpmyadmin"
    depends_on:
      - db
    ports:
     - "${PHPMYADMIN_PORT}:80"
    environment:
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
    networks:
     - localnet

  lucee:
    build: ./lucee
    container_name: "${CONTAINER_PREFIX}_lucee"
    restart: 'always'
    depends_on:
     - db
    ports: 
     - "${LUCEE_PORT}:80"
    networks:
     - localnet
    volumes:
     - ./app:/var/www/
    environment:
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
     - LUCEE_PORT
     - TIER
     - FACEBOOK_APPID
     - FACEBOOK_APPSECRET
     - DEFAULT_USER_EMAIL

  cron:
    build: ./cron
    container_name: "${CONTAINER_PREFIX}_cron"
    restart: 'always'
    depends_on:
      - db
    networks:
      - localnet
    volumes:
      - ./data/backup:/backup
    command: ["-l", "8", "-d", "8"]
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE

networks:
  localnet:
    name: "${CONTAINER_PREFIX}_net"
